"""Remove tags and journal_tags

Revision ID: 3db0738a234a
Revises: 67dddac6e31a
Create Date: 2025-03-26 02:56:38.414654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db0738a234a'
down_revision: Union[str, None] = '67dddac6e31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Drop the association table first
    op.drop_table('journal_tags')

    # Now drop the tags table
    op.drop_table('tags')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'category')
    op.create_table('journal_tags',
    sa.Column('journal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name='journal_tags_journal_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='journal_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('journal_id', 'tag_id', name='journal_tags_pkey')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('name', name='tags_name_key')
    )
    # ### end Alembic commands ###
