# """changed id field to uuid type

# Revision ID: 3e14084879c9
# Revises: a4685a2700b7
# Create Date: 2025-03-23 15:32:21.875415

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '3e14084879c9'
# down_revision: Union[str, None] = 'a4685a2700b7'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'id',
#                existing_type=sa.INTEGER(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.drop_index('ix_users_id', table_name='users')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_index('ix_users_id', 'users', ['id'], unique=False)
#     op.alter_column('users', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.INTEGER(),
#                existing_nullable=False)
#     # ### end Alembic commands ###

"""changed id field to uuid type

Revision ID: 3e14084879c9
Revises: a4685a2700b7
Create Date: 2025-03-23 15:32:21.875415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e14084879c9'
down_revision: Union[str, None] = 'a4685a2700b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="id::uuid")  # Explicit conversion to UUID
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="id::integer")  # Explicit conversion back to INTEGER
    # ### end Alembic commands ###
