"""Added sentiment field

Revision ID: 7db72ff2de6a
Revises: d4aed8c6a9a8
Create Date: 2025-03-28 08:13:13.674816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db72ff2de6a'
down_revision: Union[str, None] = 'd4aed8c6a9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sentiment', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_sentiment'), 'users', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sentiment'), table_name='users')
    op.drop_column('users', 'sentiment')
    # ### end Alembic commands ###
