"""added sentiment field to journal model

Revision ID: ae7a1e25e0fe
Revises: c14dec8ec707
Create Date: 2025-03-28 08:24:03.289071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7a1e25e0fe'
down_revision: Union[str, None] = 'c14dec8ec707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('sentiment', sa.String(), nullable=True))
    op.create_index(op.f('ix_journals_sentiment'), 'journals', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journals_sentiment'), table_name='journals')
    op.drop_column('journals', 'sentiment')
    # ### end Alembic commands ###
