"""removed sentiment field from user model

Revision ID: c14dec8ec707
Revises: 7db72ff2de6a
Create Date: 2025-03-28 08:23:18.678044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14dec8ec707'
down_revision: Union[str, None] = '7db72ff2de6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_sentiment', table_name='users')
    op.drop_column('users', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_sentiment', 'users', ['sentiment'], unique=False)
    # ### end Alembic commands ###
